=== kalebpc/windows/powershellScripts/forms/FileHash/data1.dtd
<!ELEMENT catalog (combo+)>
<!ELEMENT combo (name,option*,Description)>
<!ATTLIST combo id NMTOKEN #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT option (#PCDATA)>
<!ELEMENT Description EMPTY>

=== kalebpc/windows/powershellScripts/forms/FileHash/data.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE catalog SYSTEM "data1.dtd">
<catalog>
  <combo id="com101">
    <name>Algorithm</name>
    <option>SHA1</option>
    <option>SHA256</option>
    <option>SHA384</option>
    <option>SHA512</option>
    <option>MACTripleDES</option>
    <option>MD5</option>
    <option>RIPEMD160</option>
    <Description/>
  </combo>
</catalog>
